version: '3.8'

services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: civitas_user
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: civitas_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - civitas-network

  backend:
    build: ./backend
    depends_on:
      - db
    env_file:
      - backend/.env
    ports:
      - "8082:8000"
    networks:
      - civitas-network
    restart: unless-stopped
    # run the entrypoint module which waits for the DB and seeds schema + admin user
    command: ["python", "-m", "backend.entrypoint"]
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import socket,sys;s=socket.socket();s.settimeout(1);\ntry:\n s.connect(('127.0.0.1', 8000))\n s.close()\nexcept Exception:\n sys.exit(1)\""]
      interval: 10s
      timeout: 2s
      retries: 10
  
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        REACT_APP_API_URL: "/api/v1"
    container_name: civitas-frontend
    ports:
      - "8083:80"
    depends_on:
      - backend
    networks:
      - civitas-network
    restart: unless-stopped
    environment:
      - REACT_APP_API_URL=http://localhost:8082

networks:
  civitas-network:
    driver: bridge

volumes:
  db_data:
