
from datetime import date
from sqlalchemy import Column, Integer, String, Date, Boolean

from backend.core.ormUtil import SchemaBase



class OrmForm(SchemaBase):
    """
    This class is purely for export to other files and used to create instances, the actual tableclass will be dynamically created.
    OrmForm contains:
    - id: Integer, primary key; will be auto-incremented and generated by the DB
    - form_name: String, not nullable
    - created_at: Date, not nullable
    - is_active: Boolean, default True
    - xoev: String, not nullable
    """
    __tablename__ = "form_table"
    id = Column(Integer, primary_key=True)
    form_name = Column(String, nullable=False)
    created_at = Column(Date, default=date.today(), nullable=False)
    is_active = Column(Boolean, default=True)
    xoev = Column(String, nullable=False)
